In [1]:
#Activity 2
import sqlite3
import pandas as pd

conn = sqlite3.connect("school.db")

In [6]:
students = pd.read_csv("students.csv")
courses  = pd.read_csv("courses.csv")
enrollments = pd.read_csv("enrollments.csv")

In [19]:
students.to_sql("students", conn, if_exists="replace", index=False)
courses.to_sql("courses", conn, if_exists="replace", index=False)
enrollments.to_sql("enrollments", conn, if_exists="replace", index=False)

57

In [21]:
#Task1
pd.read_sql_query("SELECT * FROM students", conn)
pd.read_sql_query("SELECT * FROM courses", conn)
pd.read_sql_query("SELECT * FROM enrollments", conn)

    enrollment_id  student_id  course_id
0               1           1          3
1               2           1          7
2               3           2          1
3               4           2          2
4               5           2          9
5               6           3         10
6               7           3          1
7               8           4          4
8               9           4          1
9              10           4          2
10             11           5          7
11             12           5          2
12             13           6          2
13             14           7          7
14             15           7          1
15             16           7          2
16             17           8         10
17             18           9         10
18             19          10          7
19             20          10          1
20             21          10          4
21             22          11          9
22             23          12          5
23             24          13          3
24             25          13          9
25             26          14         10
26             27          15          9
27             28          15          3
28             29          16         10
29             30          17          4
30             31          17          6
31             32          17          2
32             33          18          2
33             34          18          1
34             35          18          4
35             36          19          9
36             37          19          7
37             38          20          8
38             39          20         10
39             40          21          5
40             41          21          4
41             42          22          4
42             43          23         10
43             44          24          9
44             45          24          8
45             46          25          8
46             47          25          5
47             48          26          2
48             49          26         10
49             50          26          7
50             51          27          6
51             52          28          8
52             53          29          1
53             54          29          2
54             55          30         10
55             56          30          6
56             57          30          9

In [22]:
#Task2
pd.read_sql_query("SELECT * FROM students WHERE city = 'Cairo'",conn)

      name   city  score
0  Youssef  Cairo     61
1    Salma  Cairo     94
2    Ahmed  Cairo     97
3    Karim  Cairo     65
4      Ali  Cairo     95
5     Nada  Cairo     84
6     Fady  Cairo     82
7   Sherif  Cairo     84
8   Farida  Cairo     95
9     Heba  Cairo     74

In [23]:
#Task3
pd.read_sql_query("SELECT name, city, score FROM students WHERE score >= 90 ORDER BY score DESC",conn)

      name   city  score
0   Bassem   Alex     99
1     Sara  Aswan     98
2   Mariam   Alex     98
3    Ahmed  Cairo     97
4     Dina  Luxor     97
5      Aya   Alex     96
6      Ali  Cairo     95
7   Farida  Cairo     95
8    Salma  Cairo     94
9     Hana   Giza     94
10   Rawan  Luxor     94

In [24]:
#Task4
pd.read_sql_query("SELECT name, score FROM students WHERE city = 'Giza' ORDER BY score DESC LIMIT 3",conn)

    name  score
0   Hana     94
1   Yara     87
2  Laila     74

In [25]:
#Task5
pd.read_sql_query("SELECT name, score FROM students ORDER BY score DESC LIMIT 4 OFFSET 3",conn)

    name  score
0  Ahmed     97
1   Dina     97
2    Aya     96
3    Ali     95